default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: 'truckers_development'
  username: 'postgres'
  password: 'sher'
  host: localhost
  port: 5432
